# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kostesky/Desktop/SCZR/SCZR-shapes-recognition

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kostesky/Desktop/SCZR/SCZR-shapes-recognition

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostesky/Desktop/SCZR/SCZR-shapes-recognition/CMakeFiles /home/kostesky/Desktop/SCZR/SCZR-shapes-recognition/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kostesky/Desktop/SCZR/SCZR-shapes-recognition/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named convert

# Build rule for target.
convert: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 convert
.PHONY : convert

# fast build rule for target.
convert/fast:
	$(MAKE) -f CMakeFiles/convert.dir/build.make CMakeFiles/convert.dir/build
.PHONY : convert/fast

#=============================================================================
# Target rules for targets named capture

# Build rule for target.
capture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 capture
.PHONY : capture

# fast build rule for target.
capture/fast:
	$(MAKE) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/build
.PHONY : capture/fast

src/capture.o: src/capture.cpp.o

.PHONY : src/capture.o

# target to build an object file
src/capture.cpp.o:
	$(MAKE) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/src/capture.cpp.o
.PHONY : src/capture.cpp.o

src/capture.i: src/capture.cpp.i

.PHONY : src/capture.i

# target to preprocess a source file
src/capture.cpp.i:
	$(MAKE) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/src/capture.cpp.i
.PHONY : src/capture.cpp.i

src/capture.s: src/capture.cpp.s

.PHONY : src/capture.s

# target to generate assembly for a file
src/capture.cpp.s:
	$(MAKE) -f CMakeFiles/capture.dir/build.make CMakeFiles/capture.dir/src/capture.cpp.s
.PHONY : src/capture.cpp.s

src/convert.o: src/convert.cpp.o

.PHONY : src/convert.o

# target to build an object file
src/convert.cpp.o:
	$(MAKE) -f CMakeFiles/convert.dir/build.make CMakeFiles/convert.dir/src/convert.cpp.o
.PHONY : src/convert.cpp.o

src/convert.i: src/convert.cpp.i

.PHONY : src/convert.i

# target to preprocess a source file
src/convert.cpp.i:
	$(MAKE) -f CMakeFiles/convert.dir/build.make CMakeFiles/convert.dir/src/convert.cpp.i
.PHONY : src/convert.cpp.i

src/convert.s: src/convert.cpp.s

.PHONY : src/convert.s

# target to generate assembly for a file
src/convert.cpp.s:
	$(MAKE) -f CMakeFiles/convert.dir/build.make CMakeFiles/convert.dir/src/convert.cpp.s
.PHONY : src/convert.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... convert"
	@echo "... capture"
	@echo "... src/capture.o"
	@echo "... src/capture.i"
	@echo "... src/capture.s"
	@echo "... src/convert.o"
	@echo "... src/convert.i"
	@echo "... src/convert.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

